### ISSUE TITLE
Feature: User can view library

### ISSUE THREAD

**Issue by joshangeles** [joshangeles/EmojiLib#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can view a library of emojis available from EmojiLib's database.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The User will be shown a list of emojis rendered as a library of cards with the information being provided by the EmojiLib Database.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![mobile](https://user-images.githubusercontent.com/68949703/220782700-be01446c-2605-41d5-a363-b8eebab60ecd.png)
![desktop](https://user-images.githubusercontent.com/68949703/220782743-38171001-6e07-4019-a1b4-3395d352e388.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `schema.sql` to include an "emojis" table containing the emoji name, url/path, id (auto-incrementing), and createdAt(auto-generated)
- [x] Update `data.sql` to include a couple of emojis for the purpose of rendering, ensure that they include a proper:
     - [x] `URL/Path`
     - [x] `Id`
     - [x] `Name`
     - [x] `createdAt`

### ☁️ Server Tasks

- [x] Create a basic express app listening on port `3000`
- [x] Update `server/index.js` to include an endpoint for a get request to `/api/emojis` that returns an `array` of 8 (mobile)/18 (desktop) `emoji` objects containing the emoji's `id`, `url/path`, and `name`.
     - [x] (optional) Create the callback function to return the array of `emoji` objects
- [x] Test with HTTPie
- [x] Handle all errors and respond to the clien

### ⚡ Client Tasks

- [x] Create an `EmojiCard` component that is passed an emoji object's `id, url, and name`
- [x] Create a `Load` component that loads more `EmojiCard` components
- [x] Create a `Library` component that contains 18 `EmojiCard` components and a `Load` component
- [x] Create a basic React-friendly HTML Skeleton with Bootstrap loaded in
- [x] Create a navbar matching the formatting of the wireframes.
     - [x] Mobile - Create a `Menu` component within the navbar that contains the buttons and inputs as shown within the wireframes. Ensure that the correct items are showing.
     - [x] Desktop - Create the nav-items shown in the wireframes. Ensure that the correct items are showing.
- [x] Render the resulting navbar and library to the React `root` of the page.

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
