### ISSUE TITLE
Feature: User can search for emojis

### ISSUE THREAD

**Issue by joshangeles** [joshangeles/EmojiLib#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can search the library for certain emojis.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

There will be a search bar present in the navbar at the top of the page. Upon entering a query and pressing "enter" or the search button it will query the database for all emojis that contain the query and then render and show the results.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![mobile](https://user-images.githubusercontent.com/68949703/220783256-08c773f3-d17e-4533-b019-f20257cc3cd2.png)
![desktop](https://user-images.githubusercontent.com/68949703/220783289-e75be2f8-9ffd-4af8-bb2f-c2e22eca84d0.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server/routes/get.js` to include functions that create the following endpoints:
     - [x] (optional) An endpoint that can query emojis by `emojiId`
     - [x] An endpoint that can query emojis by `name`
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Update the `HomeNavbar` component and:
     - [x]  Add an event handler to the `Search` form that will query the previously written endpoints depending on entered search parameters `onSubmit`.
     - [x] Make sure to call `e.preventDefault()` to ensure page does not refresh
     - [x] Call `setEmojis` on the returned data to set current emojis to only those that satisfy the search parameters

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
