### ISSUE TITLE
Feature: User can import emojis

### ISSUE THREAD

**Issue by joshangeles** [joshangeles/EmojiLib#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can import emojis to their server via the EmojiLib discord bot.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Upon selecting emojis within the library/search results the cards will become highlighted and an import command will appear in either the menu (mobile) or at the bottom of the page (desktop)
## 🖼️ Wireframes
> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![mobile](https://user-images.githubusercontent.com/68949703/220784430-7edc619b-3917-4891-861a-e26c4366ff8f.png)
![desktop](https://user-images.githubusercontent.com/68949703/220784472-af968636-9e19-494f-8f03-c53d096a813d.png)
## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Install the `Discord.js` module and create a new file in the `server` directory to host the bot.
- [x] Create a new discord bot on discord's website with the necessary scopes and permissions
- [x] Add the authorization token from the newly generated bot to the `.env` file
- [x] Using `discord.js`, have the bot listen for either a slash-command or a custom chat command with the keyword `import`, with the `import` command following the format of `import <EmojiName>` or `import [<Emoji1>, <Emoji2> ...<EmojiN>]`
- [x] Test within Discord
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Update the `library` component to outline each card with a white border (as shown in wireframe) to signal card selection
- [x] Create an `import` component consisting of a text area and a button, style to match wireframe and:
     - [x] Pass the selected cards from the library component to the import component, then, have the text area populated with the appropriate import command. 
     - [x] Allow the import button to copy whatever is within the `import` text-area to the clipboard.
     - [x] Style the component to be `display: none` at the appropriate breakpoints
- [x] Update the `HomeNavbar` component's `Offcanvas` to contain a similar `import` component styled matching the figma (mobile) with `display: none` at the appropriate breakpoints.

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
