### ISSUE TITLE
Feature: User can upload emojis

### ISSUE THREAD

**Issue by joshangeles** [joshangeles/EmojiLib#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can upload emojis to the EmojiLib Database.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Users can click the Upload button in the navbar (desktop) or menu (mobile) to be directed to the upload form for emojis. There they must select a name and either an image URL or upload a file image and hit upload to add it to the database.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![mobile](https://user-images.githubusercontent.com/68949703/220785052-1fdc1196-e209-48be-a56e-85983120ab99.png)
![desktop](https://user-images.githubusercontent.com/68949703/220785075-62c91873-000e-4af3-9622-eb5e74639897.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [ ] Update `server/index.js` to include a post route that includes a url and name
- [ ] Test with HTTPie
- [ ] Handle all errors and respond to the client

### ⚡ Client Tasks

- [ ] Create a React Form that takes in an emoji name and an image to be uploaded
- [ ] Update the Navbar component to take the user to the created react form when clicking the Upload Nav Link
- [ ] Update the React Form to send a post request when given a valid image file and name `on submit` and adds the uploaded emoji to the public/images directory.
- [ ] Verify that the image was also added to the database.

### 🧑‍⚕️ Clean Up Tasks

- [ ] ... 
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
